---
- name: disable swap
  import_tasks: 1_swap_disable.yaml
  - name: install k8s packages
  import_tasks: 2_k8s_modules.yaml
  - name: install containerd
  import_tasks: 3_install_containerd.yaml
  - name: install kubernetes
  import_tasks: 4_install_k8s.yaml
- name: initialize the cluster
  import_tasks: 5_initial_cluster.yaml
- name: Join cluster
  import_tasks: 6_join_cluster.yaml

 

